### ISSUE TITLE
Actions not running.

### ISSUE THREAD

**Issue by EliorYousefi** [acmerobotics/road-runner#102]
We have a problem with an action in our auto.
It enters the deposit43 and runs the deposit43traj but not the depositAction.
Image
<img width="1161" alt="actions" src="https://github.com/acmerobotics/road-runner/assets/68806839/a4cf01fe-f0e2-48bd-a7bd-1eb03700f634">
![action](https://github.com/acmerobotics/road-runner/assets/68806839/0e40dffa-60f7-4761-8062-3672bdee135a)

**Comment by rbrott** [comment]
Actions are consumable. They generally can't be reused like `depositAction` is here. I would recommend making a function that creates a deposit action and calling it multiple times.

**Comment by EliorYousefi** [comment]
it works. thanks!
