### ISSUE TITLE
Maybe duplicated points should be remoed in Profile(...)

### ISSUE THREAD

**Issue by EthanHu29** [acmerobotics/road-runner#105]
After a profile generated, I notice some data points may be duplicated, like the profile generated in line Line 63, ProfilesTest.kt, as shown in the attached picture, 
![1](https://github.com/acmerobotics/road-runner/assets/135938962/19fceb30-07c9-4f54-b9a9-5ad4cab7828c)
apparently time 1.0 points are duplicated. Will the removal of those duplicated points be convenient for future processing?

**Comment by rbrott** [comment]
> Will the removal of those duplicated points be convenient for future processing?

Not sure about "convenient", but having fewer samples will make everything run (marginally) faster. It shouldn't affect the correctness of subsequent processing.
