### ISSUE TITLE
`ManualFeedbackTuner` crash upon start when `lateralInPerTick` not set

### ISSUE THREAD

**Issue by Marlstar** [acmerobotics/road-runner#109]
Hello,
The [tuning guide](https://rr.brott.dev/docs/v1-0/tuning/#lateralpushtest-mecanum-with-drive-encoders-only) for RoadRunner 1.0 says that the `Lateral Push Test` tuning stage is only necessary for mecanum setups with **drive encoders**. There is not a section apart from this to determine `lateralInPerTick` for dead-wheel based robots.
However, if `lateralInPerTick` is left at its default value of `0`, `ManualFeedbackTuner` will crash when `start` is pressed. With a non-zero value for `lateralInPerTick`, it starts without issue (I set it to 0.1 as a test and it immediately ran).
Hence, either there is an issue behind the scenes in RoadRunner that requires `lateralInPerTick` where it is not needed, or the documentation for tuning is inaccurate.

Robot info, for context:
- Mecanum drive
- 3 dead wheel localiser

Thanks!

**Comment by rbrott** [comment]
> There is not a section apart from this to determine `lateralInPerTick` for dead-wheel based robots.

You should use [`LateralRampLogger`](https://rr.brott.dev/docs/v1-0/tuning/#lateralramplogger-mecanum-with-dead-wheels-only) to determine `lateralInPerTick` if you have dead wheels.
