### ISSUE TITLE
build.gradle.kts cleanup

### ISSUE THREAD

**Issue by thoughtless42** [acmerobotics/road-runner#116]
currently acmerobotics/road-runner/actions/build.gradle.kts
dependencies { api("com.acmerobotics.dashboard:core:0.4.7")}

this will pull in older 8.0.0 versions of 
   api "org.firstinspires.ftc:RobotCore:$min_sdk_version"
    api "org.firstinspires.ftc:Hardware:$min_sdk_version"
    api "org.firstinspires.ftc:RobotServer:$min_sdk_version"
    api "org.firstinspires.ftc:FtcCommon:$min_sdk_version"

would dependencies { api("com.acmerobotics.dashboard:core:0.4.+")}
I understand this might ripple through the other roadrunner repositories build.gradle files as well such as road-runner-ftc

**Comment by rbrott** [comment]
And the dependency on dashboard core here doesn't pull in the SDK at all: https://github.com/acmerobotics/ftc-dashboard/blob/master/DashboardCore/build.gradle
