### ISSUE TITLE
GUI feature requests.

### ISSUE THREAD

**Issue by David10238** [acmerobotics/road-runner#13]
1) support for mecanum paths and heading interporlaters.
2) the ability to define the width and length of the bot to see an outline of the bot's path similar to PathWeaver GUI, to help work around obstacles.

**Comment by rbrott** [comment]
Agreed. A new GUI and trajectory file format will be in the works soon. At the moment, I'm leaning toward switching over to FX and dropping the plugin (which requires Swing).

**Comment by rbrott** [comment]
I decided to give the old Swing GUI some love instead of building a separate FX one (I still like the idea of the plugin). Mecanum constraints (including the new lateral multiplier) and heading interpolators are supported. Your second item is on the list.
