### ISSUE TITLE
Instant acceleration when switching directions

### ISSUE THREAD

**Issue by David10238** [acmerobotics/road-runner#16]
Using this
`    private val constraints = DriveConstraints(45.0, 10.0, 0.0, 270.0.toRadians, 270.0.toRadians, 0.0)
builder
            .setReversed(true)
            .splineTo(Pose2d(-70.0, 24.0))
            .setReversed(false)
            .splineTo(Pose2d(0.0, 48.0))
`
gives this
[https://drive.google.com/file/d/1Yl0uNCpxgbBZ7f7COK7MCSRxchu3NqRT/view?usp=sharing](url)

**Comment by rbrott** [comment]
`TrajectoryBuilder#reverse()` and `TrajectoryBuilder#setReversed()` will be removed soon. Paths should not have a mix of reversed and non-reversed segments.

**Comment by rbrott** [comment]
Check out the new `TrajectoryBuilder`. It's much safer than before.
