### ISSUE TITLE
LinearInterpolator doesn't work when driving in reverse

### ISSUE THREAD

**Issue by AdrianVovk** [acmerobotics/road-runner#27]
I don't know exactly how to describe the bug; maybe I can get a video in the coming days for you.

`dt.trajectoryBuilder().splineTo(Pose2d(10.0, 0.0, PI/2), LinearInterpolater(0.0, PI/2)).build()` works as expected

`dt.trajectoryBuilder().reverse().splineTo(Pose2d(-10.0, 0.0, PI/2), LinearInterpolater(0.0, PI/2))` fails at both driving straight and turning the desired angle.

**Comment by rbrott** [comment]
Yes, this is a known issue with heading interpolators in the current API. The start and end headings for interpolators need to be reversed manually for now. A fix is already in master.

**Comment by AdrianVovk** [comment]
Ah in that case alright, thank you!
