### ISSUE TITLE
Trajectory Caching?

### ISSUE THREAD

**Issue by ToiletCommander** [acmerobotics/road-runner#37]
Is there a possible way to cache generated trajectories in a file?

**Comment by jeevan-navudu** [comment]
How are you generating these trajectories? For example, are you generating these trajectories using road-runner-plugin? If you are using a road-runner-plugin, you could save the trajectories to a file and load them later.

**Comment by rbrott** [comment]
No, there is built-in mechanism for doing that. As the other commenter mentioned, you can save trajectory configurations to disk and regenerate them on demand (although this still requires generation). The generation routine is designed to be fast enough to run at the start of every op mode.

**Comment by ToiletCommander** [comment]
Thank you for your comments!
