### ISSUE TITLE
Making Complex Splines (specifically for tank drive)

### ISSUE THREAD

**Issue by EddieDL** [acmerobotics/road-runner#47]
What is the easiest way to make custom spline motions using a tank drive. Is the best option to just stick with `toSpline()` and add additional calls to make different motions or should you consider doing something with the path so you can define the derivatives, etc.?

**Comment by rbrott** [comment]
> What is the easiest way to make custom spline motions using a tank drive. Is the best option to just stick with `toSpline()` and add additional calls to make different motions or should you consider doing something with the path so you can define the derivatives, etc.?

You should probably stick with `TrajectoryBuilder.splineTo()` unless you want more control over the endpoint derivatives.
