### ISSUE TITLE
Path Designer Unstable

### ISSUE THREAD

**Issue by FTC2875** [acmerobotics/road-runner#48]
Path Designer add-on for roadrunner completely crashes when clicking 'trajectory' tab - freezing Android Studio completely. I'm using the quickstart repo - so theoretically this shouldn't be an issue. 

EDIT: This only seems to happen when you have a non-valid trajectory, in my case I only had position values of 0,0. Make sense it wouldn't be to generate trajectory velocity for this - but it shouldn't crash the IDE completely. This is not the sole cause of this issue - I've been playing around with it only to have it be slow and crash Android Studio after a minute or so of tweaking - seems very unstable in it's current state.

**Comment by rbrott** [comment]
Thanks for the tip. The GUI/plugin were recently rewritten and have only been lightly tested. Let me know if you encounter more crashes that you can reproduce.
