### ISSUE TITLE
Documentation suggestion for the Path Designer plugin

### ISSUE THREAD

**Issue by jrasor** [acmerobotics/road-runner#53]
Road Runner also includes a simple IDEA/Android Studio “Path Designer” plugin. It is based on the GUI. Here are some instructions for building and installing it:

1. Get the latest road-runner-plugin-<version>.zip. 
  a. Download it from the current Release assets, or 
  b. Build it with ./gradlew buildPlugin. That build will go into plugin/build/distributions.
2. In Android Studio, navigate to Settings > Plugins.
3. Click the “Manage Repositories” (little gear icon in Studio 4.0) or button that reads Install plugin from disk.
4. Select road-runner-plugin-<version>.zip from where you downloaded or built it.
5. Restart Android Studio to activate plugin changes.
6. Click on "Road Runner" on the right side of the editor and the tool window should appear.

**Comment by rbrott** [comment]
Thanks for the suggestions. I incorporated some of them in the updated verbiage.
