### ISSUE TITLE
AngleUnit feature request

### ISSUE THREAD

**Issue by David10238** [acmerobotics/road-runner#6]
I would like the ability to choice the angle unit we use for positions. Degrees is more intuitive to use in pathing.

**Comment by rbrott** [comment]
Unfortunately, the use of degrees would unnecessarily complicate many of road runner's internal computations. Furthermore, adding `AngleUnit` parameters to all the angle-related public interfaces seems clunky. However, it's still relatively easy to use degrees if you would like and do the conversions yourself. `Math.toRadians()`/`Math.toDegrees()` make this relatively easy in Java (and Kotlin extension functions can make it even easier/cleaner).
