### ISSUE TITLE
Issues With Moving Backwards in Tank Drive

### ISSUE THREAD

**Issue by Dinomasater186** [acmerobotics/road-runner#60]
When I tell the robot to follow a spline or line backward it turns around and then starts spinning wildly. My best guess is that it is trying to face backwards but it also wants to face forwards to follow the path. Do you know how to fix this?

**Comment by rbrott** [comment]
Yes, there's probably with the heading and/or tangent that you've specified. Can you post the problem trajectory?

**Comment by Dinomasater186** [comment]
trajectory = drive.trajectoryBuilder(new Pose2d()).splineTo(new Vector2d(30, 30), 0).build();
drive.followTrajectory(trajectory);
SafeSleep.sleep_milliseconds(this, 500);
drive.followTrajectory(drive.trajectoryBuilder(trajectory.end(), true).splineTo(new Vector2d(0, 0), Math.toRadians(180)).build());

**Comment by Dinomasater186** [comment]
should it be 0 instead of 180?

**Comment by rbrott** [comment]
That looks correct to me for v0.5.1+. Are you using any feedback? If so, I would temporarily turn it off and check what happens with feedforward alone.

**Comment by Dinomasater186** [comment]
Thanks for the help. We have fixed this by changing the TankPIDVAFollower so that the cross track controller uses the heading error.

**Comment by rbrott** [comment]
Oh I actually helped someone earlier with this problem. I wouldn't recommend switching to heading control; minimizing cross-track error is more important. Here's a patched version of the follower that fixes the sign of the error: https://hastebin.com/neqafeqehi.kotlin

**Comment by rbrott** [comment]
Tank PIDVA follower patched in 230cbf616ab166b25d8ce0e6d5f9cb6bca16278d.
