### ISSUE TITLE
Add way to export code for robot to run

### ISSUE THREAD

**Issue by lavalleeale** [acmerobotics/road-runner#62]
I am not sure if this is possible, but it would be really cool to just have to press a button to get the code that the robot can run

**Comment by rbrott** [comment]
The [quickstart](https://github.com/acmerobotics/road-runner-quickstart) is the closest you'll com to plug and play with Road Runner. The tuning process could be made easier with better automated routines, but there are still parameters that need to be empirically determined on a robot-specific basis.

Perhaps you would be interested in [this autonomous creator](https://ftcchad.com/) that produces ready-to-use op modes.
