### ISSUE TITLE
Vuforia as a Localizer

### ISSUE THREAD

**Issue by slylockfox** [acmerobotics/road-runner#72]
I wonder if anyone has tried to make a Localizer that integrates position data from Vuforia?

**Comment by rbrott** [comment]
Here's an untested sample that attempts to integrate Vuforia for localization: https://github.com/acmerobotics/road-runner-quickstart/blob/ab08fd6986649aee4073d161e169d6e11dc1891d/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/ComplementaryVuforiaLocalizer.java

**Comment by slylockfox** [comment]
Thank you @rbrott !  I'll give it a try.

**Comment by Anti-Shulk** [comment]
How well does it work?
