### ISSUE TITLE
FTC Dashboard Wifi Problem

### ISSUE THREAD

**Issue by SomeoneSketchySync** [acmerobotics/road-runner#75]
We are facing this strange error in accessing the FTC Dashboard after the 7.1 upgrade. We wanted to retune RoadRunner because of a slight mechanical redesign and ended up with this error. We also updated to the new release of RoadRunner.

<img width="1631" alt="Screen Shot 2022-02-06 at 7 19 27 PM" src="https://user-images.githubusercontent.com/76824572/152708011-78167968-469c-4da6-a957-f760ebc1686d.png">

Thanks,
AP, Team 19643

**Comment by rbrott** [comment]
Dash may be somehow disabled. Try re-enabling it first. If it still doesn't work, open [dev tools](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools) and capture the network tab (specifically the websocket at the end) and any console output.

**Comment by SomeoneSketchySync** [comment]
Could you please let me know how to re-enable the dashboard? Thanks for the speedy reply!

**Comment by SomeoneSketchySync** [comment]
Thanks! I just figured it out and now it works. I reenabled it via the Driver Station where under the TeleOp section there was an option to Enable/Disable the dashboard.
