### ISSUE TITLE
1.0.0 Beta 5 I am having an issue where past a certain point in our auto when we try to follow a spline it goes fine until the last little bit where it corrects to a heading about  30 degrees off

### ISSUE THREAD

**Issue by ayoda1122** [acmerobotics/road-runner#99]
I have an abstract class where most of the path generation happens but for the paths that are generated in the actual auto, It seems to act up when I try to add any movement. The coordinates don't line up anymore and the heading gets pretty far off after a correction. I am feeding it drive.pos for the start position for this action, but when I tried to feed it the actual position it threw an error but I can remember the error. 
In the abstract class, I have public actions that return my actions and I am doing the same with the actions in the class but have had multiple issues with the localizer getting off, but if I move the same paths to the abstract class and run them as a part of the previous action it works well but for our system, we need to have them separate preferably.

**Comment by ayoda1122** [comment]
This is the code under the abstract class
![image](https://github.com/acmerobotics/road-runner/assets/145617680/574cb4cb-9895-4cc3-8028-2e792e8f10f1)
![image](https://github.com/acmerobotics/road-runner/assets/145617680/0911f7a0-26c3-4c0a-9f09-a90b26cceb12)

**Comment by ayoda1122** [comment]
I assume that I am not giving it the correct start position but when I try to use 
new Pose2d(new Vector2d(55, -20), -PI/2) *not sure if correct values but this was the syntax I tried*
I kept running into an error.

**Comment by rbrott** [comment]
I'm having trouble following all of this. Can you start by describing one particular problem and include a minimal code example?

**Comment by ayoda1122** [comment]
The main problem is towards the end of our code the coordinates and headings stop lining up with the field. As in if i try to go to a different point it ends up trying to go to a completely different point usually through the wall. It would seem that this happens for all but our first action.

**Comment by ayoda1122** [comment]
![image](https://github.com/acmerobotics/road-runner/assets/145617680/7e909023-5489-484a-97ed-cc963d218d4c)
This is the top section of the auto base mostly for non Roadrunner things.

**Comment by ayoda1122** [comment]
![image](https://github.com/acmerobotics/road-runner/assets/145617680/6811f6c8-aec2-44e2-8ea9-e386fcb868c9)
Still in Auto base does the logic for spike position

**Comment by ayoda1122** [comment]
![image](https://github.com/acmerobotics/road-runner/assets/145617680/7c968fde-fc0e-4071-8122-cf4bf5a05c42)
![image](https://github.com/acmerobotics/road-runner/assets/145617680/ff0fdaab-5198-4918-8e2b-50b51564a7ae)
This is the action for spike left specifically in auto base

**Comment by ayoda1122** [comment]
![image](https://github.com/acmerobotics/road-runner/assets/145617680/d65c25d8-a0d0-4c74-8792-69da8a7fb2f8)
top of Red right code
![image](https://github.com/acmerobotics/road-runner/assets/145617680/fdca6ad0-9a63-4da8-966f-ec5b885350e0)
This is the action that is in Red Right

**Comment by ayoda1122** [comment]
![Uploading image.png…]()
And then the run code

**Comment by ayoda1122** [comment]
![image](https://github.com/acmerobotics/road-runner/assets/145617680/c16db4bd-bc7a-434b-b30f-d4861ca282f9)
and then run code
